import test from 'node:test';
import assert from 'node:assert/strict';
import { parseCSV, normalizeRows, filterRecords, analyzeRecords, detectStoppages, exportCSV } from '../src/analytics.js';
import { parseXLSX } from '../src/xlsx.js';
import { deflateRawSync } from 'node:zlib';

test('CSV parser handles quoted commas, escaped quotes and line breaks',()=>{const rows=parseCSV('日期,原始记录\r\n2026-09-07,"完成, 正常"\n2026-09-08,"他说""停工""\n两行"');assert.equal(rows[0]['原始记录'],'完成, 正常');assert.equal(rows[1]['原始记录'],'他说"停工"\n两行');});
test('normalizes aliases, numbers and dates and removes unusable rows',()=>{const rows=normalizeRows([{date:'2026/09/07',workshop:'Grinding',actual_progress:'25%',chinese_staff:'1,200',record:'work'}, {date:'bad'}],'r.csv');assert.equal(rows.length,1);assert.deepEqual([rows[0].date,rows[0].actualProgress,rows[0].chineseStaff],['2026-09-07',25,1200]);});
test('normalizes Excel serial dates',()=>{const rows=normalizeRows([{'日期':46272,'车间':'A','原始记录':'x'}]);assert.equal(rows[0].date,'2026-09-07');});
test('filters by inclusive date, workshop and process',()=>{const rows=[{date:'2026-09-01',workshop:'A',process:'P'},{date:'2026-09-02',workshop:'B',process:'P'}];assert.equal(filterRecords(rows,{date:'2026-09-01',workshop:'A',process:'P'}).length,1);});
test('calculates latest progress, concrete and staff change without duplicating staff',()=>{const rows=normalizeRows([
 {'日报名称':'R1','日期':'2026-09-01','车间':'A','工序':'P','WBS权重':'1','计划进度':'20','实际进度':'10','实际完成工作量':'5','累计完成量':'10','工作量单位':'m³','人员口径':'项目总人数','中方人员':'4','属地人员':'8','原始记录':'x'},
 {'日报名称':'R2','日期':'2026-09-02','车间':'A','工序':'P','WBS权重':'1','计划进度':'30','实际进度':'20','实际完成工作量':'7','累计完成量':'17','工作量单位':'m³','人员口径':'项目总人数','中方人员':'5','属地人员':'10','原始记录':'x'},
 {'日报名称':'R2','日期':'2026-09-02','车间':'B','工序':'Q','WBS权重':'1','计划进度':'40','实际进度':'30','实际完成工作量':'3','累计完成量':'20','工作量单位':'t','人员口径':'项目总人数','中方人员':'5','属地人员':'10','原始记录':'x'}]);const a=analyzeRecords(rows);assert.equal(a.kpis.planned,35);assert.equal(a.kpis.actual,25);assert.equal(a.quantityGroups.length,2);assert.equal(a.quantityGroups.find(x=>x.unit==='m³').daily,7);assert.equal(a.quantityGroups.find(x=>x.unit==='t').daily,3);assert.equal(a.kpis.totalStaff,15);assert.equal(a.kpis.staffDelta,3);});
test('aggregates progress into day, week and month buckets',()=>{const rows=normalizeRows([{'日期':'2026-09-01','车间':'A','实际进度':'10','原始记录':'x'},{'日期':'2026-09-02','车间':'A','实际进度':'12','原始记录':'x'},{'日期':'2026-10-01','车间':'A','实际进度':'20','原始记录':'x'}]);assert.equal(analyzeRecords(rows,'day').timeline.length,3);assert.equal(analyzeRecords(rows,'week').timeline.length,2);assert.equal(analyzeRecords(rows,'month').timeline.length,2);});
test('detects three reported stoppages and preserves evidence',()=>{const rows=normalizeRows([1,2,3].map(d=>({'日报名称':`日报${d}`,'日期':`2026-09-0${d}`,'车间':'A','工序':'基础','实际进度':'10','当日混凝土':'0','工作状态':'停工','原始记录':`证据${d}`})));const result=detectStoppages(rows);assert.equal(result.length,1);assert.equal(result[0].days,3);assert.equal(result[0].evidence[2].reportName,'日报3');assert.equal(result[0].evidence[2].rawRecord,'证据3');});
test('does not treat two stoppages or missing neutral record as continuous three',()=>{const rows=normalizeRows([{'日期':'2026-09-01','车间':'A','工序':'P','工作状态':'停工','原始记录':'1'},{'日期':'2026-09-02','车间':'A','工序':'P','工作状态':'施工中','原始记录':'2'},{'日期':'2026-09-03','车间':'A','工序':'P','工作状态':'停工','原始记录':'3'},{'日期':'2026-09-04','车间':'A','工序':'P','工作状态':'停工','原始记录':'4'}]);assert.equal(detectStoppages(rows).length,0);});
test('creates lag risk at five percentage points',()=>{const rows=normalizeRows([{'日报名称':'R','日期':'2026-09-01','车间':'A','工序':'P','计划进度':'20','实际进度':'15','原始记录':'x'}]);assert.equal(analyzeRecords(rows).risks[0].title,'关键节点滞后');});
test('does not publish overall progress without WBS weights',()=>{const rows=normalizeRows([{'日期':'2026-09-01','车间':'A','工序':'P','计划进度':'20','实际进度':'15','原始记录':'x'}]);const result=analyzeRecords(rows);assert.equal(result.kpis.planned,null);assert.equal(result.kpis.actual,null);});
test('zero quantity alone does not imply stoppage when crew is present',()=>{const rows=normalizeRows([1,2,3].map(d=>({'日期':`2026-09-0${d}`,'车间':'A','工序':'P','实际进度':'10','实际完成工作量':'0','中方人员':'2','原始记录':'施工准备'})));assert.equal(detectStoppages(rows).length,0);});
test('links multi-day stoppage to a potential installation impact',()=>{const rows=normalizeRows([1,2,3].map(d=>({'日报名称':`R${d}`,'日期':`2026-09-0${d}`,'车间':'磨房','工序':'设备基础','工作状态':'停工','原始记录':'停工'})));const result=analyzeRecords(rows);assert.equal(result.installationImpacts.length,1);assert.match(result.installationImpacts[0].detail,/12 月安装目标/);assert.equal(result.installationImpacts[0].confidence,'待人工评估');});
test('CSV export quotes evidence containing commas',()=>{const csv=exportCSV([{reportName:'R,1',date:'2026-09-01'}]);assert.match(csv,/"R,1"/);});

function zip(files){const locals=[],centrals=[];let offset=0;for(const [name,text] of Object.entries(files)){const nameBytes=Buffer.from(name),raw=Buffer.from(text),data=deflateRawSync(raw),local=Buffer.alloc(30);local.writeUInt32LE(0x04034b50);local.writeUInt16LE(20,4);local.writeUInt16LE(8,8);local.writeUInt32LE(data.length,18);local.writeUInt32LE(raw.length,22);local.writeUInt16LE(nameBytes.length,26);locals.push(local,nameBytes,data);const central=Buffer.alloc(46);central.writeUInt32LE(0x02014b50);central.writeUInt16LE(20,6);central.writeUInt16LE(8,10);central.writeUInt32LE(data.length,20);central.writeUInt32LE(raw.length,24);central.writeUInt16LE(nameBytes.length,28);central.writeUInt32LE(offset,42);centrals.push(central,nameBytes);offset+=local.length+nameBytes.length+data.length;}const centralData=Buffer.concat(centrals),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(Object.keys(files).length,8);end.writeUInt16LE(Object.keys(files).length,10);end.writeUInt32LE(centralData.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...locals,centralData,end]);}
test('imports first XLSX worksheet with shared and inline strings',async()=>{const fixture=zip({'xl/sharedStrings.xml':'<sst><si><t>日期</t></si><si><t>车间</t></si></sst>','xl/worksheets/sheet1.xml':'<worksheet><sheetData><row><c r="A1" t="s"><v>0</v></c><c r="B1" t="s"><v>1</v></c></row><row><c r="A2" t="inlineStr"><is><t>2026-09-07</t></is></c><c r="B2" t="inlineStr"><is><t>粉磨车间</t></is></c></row></sheetData></worksheet>'});const rows=await parseXLSX(fixture.buffer.slice(fixture.byteOffset,fixture.byteOffset+fixture.byteLength));assert.deepEqual(rows,[{'日期':'2026-09-07','车间':'粉磨车间'}]);});
