import test from 'node:test';
import assert from 'node:assert/strict';
import { loadCloudConfig, SupabaseCloudRepository, tokenFromLocation } from '../src/cloud.js';

test('loads only browser-safe cloud configuration',async()=>{const config=await loadCloudConfig(async()=>({ok:true,json:async()=>({supabaseUrl:'https://example.supabase.co',supabaseAnonKey:'anon',ocrEnabled:true})}));assert.equal(config.supabaseAnonKey,'anon');assert.equal(config.ocrEnabled,true);});
test('binds fetch to the global object for Magic Link login',async()=>{const calls=[];function browserFetch(url,options={}){assert.strictEqual(this,globalThis);calls.push({url,options});return Promise.resolve({ok:true});}const repo=new SupabaseCloudRepository({supabaseUrl:'https://db.example',supabaseAnonKey:'anon',storageBucket:'reports'},{fetchImpl:browserFetch});await repo.requestMagicLink('engineer@example.com','https://app.example/auth');assert.equal(calls.length,1);assert.equal(calls[0].url,'https://db.example/auth/v1/otp');assert.deepEqual(JSON.parse(calls[0].options.body),{email:'engineer@example.com',options:{emailRedirectTo:'https://app.example/auth'}});});
test('uses the bound fetch and user token across REST, storage and signed URL operations',async()=>{const calls=[];function browserFetch(url,options={}){assert.strictEqual(this,globalThis);calls.push({url,options});if(url.startsWith('data:'))return Promise.resolve({ok:true,blob:async()=>new Blob(['image'],{type:'image/jpeg'})});if(url.includes('/object/sign/'))return Promise.resolve({ok:true,text:async()=>'',json:async()=>({signedURL:'/object/sign/reports/photo.jpg?token=signed'})});return Promise.resolve({ok:true,text:async()=>'',json:async()=>({})});}const repo=new SupabaseCloudRepository({supabaseUrl:'https://db.example',supabaseAnonKey:'anon',storageBucket:'reports'},{accessToken:'user-jwt',fetchImpl:browserFetch}),pdf=Object.assign(new Blob(['%PDF'],{type:'application/pdf'}),{name:'daily.pdf'}),images=[{imageId:'photo-1',sourceFile:'daily.pdf',pageNumber:1,dataUrl:'data:image/jpeg;base64,aW1hZ2U=',mimeType:'image/jpeg'}];await repo.request('/rest/v1/daily_reports');await repo.uploadOriginal(pdf,'batch');const uploaded=await repo.uploadEvidenceImages(images,'batch');const signed=await repo.signedUrl(images[0].objectPath);await repo.saveBatch([{id:'report-1',date:'2026-09-07',sourceFile:'daily.pdf'}],images,{importId:'batch',files:['daily.pdf'],uploadPaths:uploaded.paths});const supabaseCalls=calls.filter(call=>call.url.startsWith('https://db.example'));assert.ok(supabaseCalls.length>=7);assert.ok(supabaseCalls.every(call=>call.options.headers.Authorization==='Bearer user-jwt'));assert.equal(uploaded.failures.length,0);assert.match(images[0].objectPath,/evidence\/photo-1\.jpg$/);assert.equal(signed,'https://db.example/storage/v1/object/sign/reports/photo.jpg?token=signed');assert.ok(calls.some(call=>call.url.includes('/daily_reports')));assert.ok(calls.some(call=>call.url.includes('/image_evidence')));assert.ok(calls.some(call=>call.url.includes('/import_audits')));});
test('cloud repository uploads original PDF and normalized batch with bearer token',async()=>{const calls=[],fetchImpl=async(url,options={})=>{calls.push({url,options});return {ok:true,text:async()=>'',blob:async()=>new Blob(['x'],{type:'image/jpeg'})};},repo=new SupabaseCloudRepository({supabaseUrl:'https://db.example',supabaseAnonKey:'anon',storageBucket:'reports'},{accessToken:'user-jwt',fetchImpl});const file=new Blob(['%PDF']);Object.defineProperty(file,'name',{value:'daily.pdf'});await repo.uploadOriginal(file,'batch');await repo.saveBatch([{id:'r1',date:'2026-09-07',workshop:'A',process:'P',sourceFile:'daily.pdf'}],[],{importId:'batch',files:['daily.pdf'],uploadPaths:['path']});assert.match(calls[0].url,/storage\/v1\/object/);assert.equal(calls[0].options.headers.Authorization,'Bearer user-jwt');assert.ok(calls.some(call=>call.url.includes('daily_reports')));assert.ok(calls.some(call=>call.url.includes('import_audits')));});
test('extracts Supabase access token from auth callback fragment',()=>{assert.equal(tokenFromLocation({hash:'#access_token=abc&expires_in=3600'}),'abc');assert.equal(tokenFromLocation({hash:'#entry'}),'');});
test('batch upload reports partial failure and uses idempotent upsert for retry',async()=>{let failedOnce=true;const calls=[],repo=new SupabaseCloudRepository({supabaseUrl:'https://db.example',supabaseAnonKey:'anon',storageBucket:'reports'},{accessToken:'jwt',fetchImpl:async(url,options={})=>{calls.push(options);if(url.includes('bad.pdf')&&failedOnce){failedOnce=false;return {ok:false,text:async()=> 'temporary'};}return {ok:true,text:async()=>''};}}),files=[Object.assign(new Blob(['a']),{name:'good.pdf'}),Object.assign(new Blob(['b']),{name:'bad.pdf'})];const first=await repo.uploadOriginals(files,'stable');assert.equal(first.paths.length,1);assert.equal(first.failures.length,1);const retry=await repo.uploadOriginals(files,'stable');assert.equal(retry.failures.length,0);assert.ok(calls.every(call=>call.headers['x-upsert']==='true'));});
test('large PDF is streamed as a Blob instead of serialized into browser storage',async()=>{let uploadedBody;const repo=new SupabaseCloudRepository({supabaseUrl:'https://db.example',supabaseAnonKey:'anon',storageBucket:'reports'},{accessToken:'jwt',fetchImpl:async(url,options)=>{uploadedBody=options.body;return {ok:true,text:async()=>''};}}),large=Object.assign(new Blob([new Uint8Array(8*1024*1024)],{type:'application/pdf'}),{name:'large.pdf'});await repo.uploadOriginal(large,'large-batch');assert.strictEqual(uploadedBody,large);assert.equal(uploadedBody.size,8*1024*1024);});
