import test from 'node:test';
import assert from 'node:assert/strict';
import { parsePDF, mapPDFText } from '../src/pdf.js';
import { EvidenceStore } from '../src/storage.js';
import { analyzeImageMetadata, findEvidenceConflicts } from '../src/image-analysis.js';

class MemoryStorage { constructor(){this.data=new Map()} getItem(k){return this.data.get(k)??null} setItem(k,v){this.data.set(k,v)} }
function fixturePDF({withText=true,withImage=true}={}) { const content=withText?'BT (Date: 2026-09-07 Workshop: Grinding Process: Foundation Planned Progress: 20 Actual Progress: 12 Chinese Staff: 8 Local Staff: 30 Status: stopped) Tj ET':'';const parts=['%PDF-1.4\n','1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n','2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n',`3 0 obj\n<< /Type /Page /Parent 2 0 R /Contents 4 0 R /Resources << /XObject << /Im1 ${withImage?'5':'9'} 0 R >> >> >>\nendobj\n`,`4 0 obj\n<< /Length ${content.length} >>\nstream\n${content}\nendstream\nendobj\n`];if(withImage)parts.push('5 0 obj\n<< /Type /XObject /Subtype /Image /Width 1 /Height 1 /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length 4 >>\nstream\n',Buffer.from([0xff,0xd8,0xff,0xd9]),'\nendstream\nendobj\n');parts.push('%%EOF');const buffer=Buffer.concat(parts.map(x=>Buffer.isBuffer(x)?x:Buffer.from(x,'latin1')));return buffer.buffer.slice(buffer.byteOffset,buffer.byteOffset+buffer.byteLength);}

test('maps extracted PDF labels into the shared report structure',()=>{const rows=mapPDFText('Date: 2026-09-07 Workshop: Grinding Process: Foundation Actual Progress: 12 Status: stopped',{sourceFile:'daily.pdf',pageNumber:2});assert.equal(rows[0].date,'2026-09-07');assert.equal(rows[0].workshop,'Grinding');assert.equal(rows[0].actualProgress,12);assert.equal(rows[0].sourceType,'pdf');assert.equal(rows[0].pageNumber,2);});
test('imports PDF text and embedded image with provenance',async()=>{const result=await parsePDF(fixturePDF(),'daily.pdf');assert.equal(result.records.length,1);assert.equal(result.records[0].localStaff,30);assert.equal(result.images.length,1);assert.match(result.images[0].dataUrl,/^data:image\/jpeg;base64,/);assert.deepEqual([result.images[0].sourceFile,result.images[0].pageNumber,result.images[0].imageIndex],['daily.pdf',1,1]);assert.ok(result.images[0].imageId);});
test('degrades safely when PDF has no mapped fields or supported images',async()=>{const result=await parsePDF(fixturePDF({withText:false,withImage:false}),'empty.pdf');assert.deepEqual(result.records,[]);assert.deepEqual(result.images,[]);assert.ok(result.diagnostics.warnings.length);await assert.rejects(()=>parsePDF(new TextEncoder().encode('not pdf').buffer),/有效/);});
test('stores and manually corrects image evidence',()=>{const storage=new MemoryStorage(),store=new EvidenceStore(storage),image={imageId:'i1',sourceFile:'x.pdf',pageNumber:1,imageIndex:1,tags:[]};assert.equal(store.merge([image,image]).added,1);store.update('i1',{relatedWorkshop:'Grinding',critical:true,manualReviewed:true});assert.equal(store.all()[0].critical,true);assert.equal(store.all()[0].relatedWorkshop,'Grinding');});
test('metadata analysis is explicitly low-confidence inference and detects conflicts',()=>{const analysis=analyzeImageMetadata({nearbyText:'设备到货，现场卸车'});assert.equal(analysis.scene,'设备到货');assert.equal(analysis.evidenceType,'AI推断');assert.equal(analysis.reviewRecommended,true);const conflicts=findEvidenceConflicts({status:'停工'},[{imageId:'i',scene:'施工中'}]);assert.equal(conflicts.length,1);});
