export async function loadCloudConfig(fetchImpl=fetch){const response=await fetchImpl('/api/config',{headers:{Accept:'application/json'}});if(!response.ok)throw new Error(`云端配置读取失败：${response.status}`);return response.json();}
const clean=name=>name.replace(/[^a-zA-Z0-9._-]/g,'_');
const fileKey=async name=>{const hash=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(name)));return `${Array.from(hash).map(n=>n.toString(16).padStart(2,'0')).join('')}-${clean(name).slice(-100)}`;};
export class SupabaseCloudRepository{
  constructor(config,{accessToken='',fetchImpl=fetch,auth=null}={}){this.config=config;this.token=accessToken;this.auth=auth;this.fetch=(...args)=>Reflect.apply(fetchImpl,globalThis,args);}
  get configured(){return Boolean(this.config.supabaseUrl&&this.config.supabaseAnonKey);}
  headers(extra={}){return {apikey:this.config.supabaseAnonKey,Authorization:`Bearer ${this.token||this.config.supabaseAnonKey}`,...extra};}
  async request(path,options={}){if(!this.configured)throw new Error('尚未配置 Supabase');if(this.auth)this.token=(await this.auth.current())?.access_token||'';if(!this.token)throw new Error('请先登录；匿名用户不能读写项目文件或数据');const response=await this.fetch(`${this.config.supabaseUrl}${path}`,{...options,headers:this.headers(options.headers)});if(!response.ok)throw new Error(`Supabase ${response.status}: ${await response.text()}`);return response;}
  async requestMagicLink(email,redirectTo=location.origin){if(this.auth)return this.auth.signIn(email,redirectTo);const response=await this.fetch(`${this.config.supabaseUrl}/auth/v1/otp?redirect_to=${encodeURIComponent(redirectTo)}`,{method:'POST',headers:{apikey:this.config.supabaseAnonKey,'Content-Type':'application/json'},body:JSON.stringify({email,create_user:false})});if(!response.ok)throw new Error(`登录邮件发送失败：${response.status}`);}
  async uploadOriginal(file,importId){const path=`khayrat/${importId}/${await fileKey(file.webkitRelativePath||file.name)}`;await this.request(`/storage/v1/object/${this.config.storageBucket}/${path}`,{method:'POST',headers:{'Content-Type':file.type||'application/pdf','x-upsert':'true'},body:file});return path;}
  async uploadOriginals(files,importId,onProgress=()=>{}){const paths=[],failures=[];for(let index=0;index<files.length;index++){const file=files[index];try{paths.push(await this.uploadOriginal(file,importId));onProgress({type:'pdf',completed:index+1,total:files.length,name:file.webkitRelativePath||file.name});}catch(error){failures.push({name:file.webkitRelativePath||file.name,error:error.message});onProgress({type:'pdf',completed:index+1,total:files.length,name:file.name,error:error.message});}}return {paths,failures};}
  async uploadEvidenceImages(images,importId,onProgress=()=>{}){const paths=[],failures=[];for(let index=0;index<images.length;index++){const image=images[index];if(!image.dataUrl)continue;try{const response=await this.fetch(image.dataUrl),blob=await response.blob(),extension=image.mimeType==='image/png'?'png':image.mimeType==='image/jp2'?'jp2':'jpg',path=`khayrat/${importId}/evidence/${clean(image.imageId)}.${extension}`;await this.request(`/storage/v1/object/${this.config.storageBucket}/${path}`,{method:'POST',headers:{'Content-Type':image.mimeType||blob.type,'x-upsert':'true'},body:blob});image.objectPath=path;paths.push(path);onProgress({type:'image',completed:index+1,total:images.length,name:image.imageId});}catch(error){failures.push({imageId:image.imageId,error:error.message});onProgress({type:'image',completed:index+1,total:images.length,name:image.imageId,error:error.message});}}return {paths,failures};}
  async signedUrl(path,expiresIn=3600){const response=await this.request(`/storage/v1/object/sign/${this.config.storageBucket}/${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expiresIn})});const result=await response.json();if(!result.signedURL)throw new Error('私有文件签名地址未返回');return result.signedURL.startsWith('http')?result.signedURL:`${this.config.supabaseUrl}/storage/v1${result.signedURL}`;}
  async saveBatch(records,images,{importId,files,uploadPaths}){if(records.some(r=>!r.id)||images.some(i=>!i.imageId))throw new Error('记录缺少稳定 ID，拒绝保存');const reportRows=records.map(r=>({id:r.id,project_id:'khayrat',report_date:r.date||null,workshop:r.workshop||null,process:r.process||null,activity_id:r.activityId||null,source_file:r.sourceFile||r.source,payload:r,updated_at:new Date().toISOString()}));const imageRows=images.map(({dataUrl,blob,rawPdf,signedUrl,...i})=>({image_id:i.imageId,project_id:'khayrat',report_id:i.relatedRecordId||null,source_file:i.sourceFile,page_number:i.pageNumber,payload:i,updated_at:new Date().toISOString()}));if(reportRows.length)await this.request('/rest/v1/daily_reports?on_conflict=id',{method:'POST',headers:{'Content-Type':'application/json',Prefer:'resolution=merge-duplicates'},body:JSON.stringify(reportRows)});if(imageRows.length)await this.request('/rest/v1/image_evidence?on_conflict=image_id',{method:'POST',headers:{'Content-Type':'application/json',Prefer:'resolution=merge-duplicates'},body:JSON.stringify(imageRows)});await this.request('/rest/v1/import_audits?on_conflict=import_id',{method:'POST',headers:{'Content-Type':'application/json',Prefer:'resolution=merge-duplicates'},body:JSON.stringify({import_id:importId,files,result:{records:reportRows.length,images:imageRows.length,uploadPaths}})});}
  async loadProject(){
    const read=async table=>{const rows=[];for(let offset=0;;offset+=500){const response=await this.request(`/rest/v1/${table}?project_id=eq.khayrat&select=*&order=${table==='daily_reports'?'id':'image_id'}&offset=${offset}&limit=500`);const page=await response.json();if(!Array.isArray(page))throw new Error('云端数据格式错误');rows.push(...page);if(page.length<500)break;}return rows;};
    const [reports,images]=await Promise.all([read('daily_reports'),read('image_evidence')]);
    return {records:reports.map(r=>({...r.payload,id:r.id})),images:images.map(i=>({...i.payload,imageId:i.image_id}))};
  }

}
export function tokenFromLocation(locationLike=location){const params=new URLSearchParams((locationLike.hash||'').replace(/^#/,''));return params.get('access_token')||'';}
