const DB_NAME='khayrat-project-data', DB_VERSION=1;
export class ProjectDatabase {
  constructor(indexedDBImpl=globalThis.indexedDB){this.indexedDB=indexedDBImpl;this.dbPromise=null;}
  open(){if(!this.indexedDB)return Promise.reject(new Error('当前浏览器不支持 IndexedDB'));if(this.dbPromise)return this.dbPromise;this.dbPromise=new Promise((resolve,reject)=>{const request=this.indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains('reports'))db.createObjectStore('reports',{keyPath:'id'});if(!db.objectStoreNames.contains('images'))db.createObjectStore('images',{keyPath:'imageId'});if(!db.objectStoreNames.contains('imports'))db.createObjectStore('imports',{keyPath:'importId'});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});return this.dbPromise;}
  async all(storeName){const db=await this.open();return new Promise((resolve,reject)=>{const request=db.transaction(storeName).objectStore(storeName).getAll();request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
  async load(){const [records,images,imports]=await Promise.all(['reports','images','imports'].map(name=>this.all(name)));return {records,images,imports};}
  async replace(records,images){const db=await this.open();return new Promise((resolve,reject)=>{const tx=db.transaction(['reports','images'],'readwrite'),reports=tx.objectStore('reports'),pictures=tx.objectStore('images');reports.clear();pictures.clear();records.forEach(r=>reports.put(r));images.forEach(({dataUrl,blob,rawPdf,...metadata})=>pictures.put(metadata));tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('IndexedDB 事务已中止'));});}
  async addImport(audit){const db=await this.open();return new Promise((resolve,reject)=>{const tx=db.transaction('imports','readwrite');tx.objectStore('imports').put(audit);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}
}
